investigate_person:
  description: >
    According to the corporate email {corporate_email}, search for full name, company, job tittle and/or area of expertise to whom does it belong the email.
  expected_output: >
    In English, a short description of the person, like "This corporate email looks to belong to John Doe/Jone Doe, here's information about him/her:"
    Follow a strict order for the answer:
    - Short description
    - Email: 
    - Full Name:
    - Company:
    - Job Tittle:
    - Area of Expertise:
  agent: web_searcher

services_analysis:
  description: >
    Analyze all the services provided by Ricoh Latin America.
  expected_output: >
    In English, the name of each service followed by a description of what it is about.
  agent: services_expert

make_match:
  description: >
    Make a match between the person researched and the services analyzed.
  expected_output: >
    In English, a brief explanation of how the match was made, then list the services and describe for what is used each service and why would match with the person's job tittle.
  agent: services_recommender
